public class KnownSuffixes {
    public static final String[][] KNOWN_SUFFIXES = new String[][]{

            {"junior", "jr.", "jr" },
            {"senior", "sr.", "sr"},
            {"second", "2nd", "ii", "i.i.", "The Second"},
            {"third", "3rd", "iii", "i.i.i.", "The Third"},
            {"fourth", "4th", "iv", "i.v.", "The Fourth"},
            {"fifth", "5th", "v", "v.", "The Fifth"},
            {"sixth", "6th", "vi", "v.i.", "The Sixth"},
            {"esquire", "esq", "esq."},
            {"cpa", "c.p.a"},
            {"dc", "d.c."},
            {"dds", "d.d.s."},
            {"vm", "v.m."},
            {"jd", "j.d."},
            {"md", "m.d."},
            {"phd", "ph.d"},
            {"cfa", "c.f.a"},
            {"pe", "p.e."},
            {"do", "d.o."},
            {"dvm", "d.v.m."},
            {"ed.d", "edd"},
            {"od", "o.d."},
            {"ret", "ret.", "retd.", "retd", "retired"},
            {"r.n", "rn"},
            {"usaf", "u.s.a.f."},
            {"usmc", "u.s.m.c."},
            {"usa", "u.s.a."},
            {"usafr", "u.s.a.f.r."},
            {"usar", "u.s.a.r."},
            {"uscg", "u.s.c.g."},
            {"usmcr", "u.s.m.c.r."},
            {"usn", "u.s.n."},
            {"usnr", "u.s.n.r."},
            {"atty", "atty."},
            {"ddm", "d.d.m."},
            {"dmd", "d.m.d."},
            {"dpm","d.p.m."},
            {"facal","f.a.c.a.l."},
            {"facan","f.a.c.a.n."},
            {"facc","f.a.c.c."},
            {"facd","f.a.c.d."},
            {"facfo","f.a.c.f.o."},
            {"facg","f.a.c.g."},
            {"facs","f.a.c.s."},
            {"pc","p.c."},
            {"mds","m.d.s."},
            {"mr", "ms","mrs","mrs.", "mr.", "ms."},
            {"dr.", "dr"},
            {"Prof", "prof."}

    };
}
